// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $contact from "./routes/contact.tsx";
import * as $custom from "./routes/custom.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $sustainability from "./routes/sustainability.tsx";
import * as $AddToCartButton from "./islands/AddToCartButton.tsx";
import * as $CategoryFilter from "./islands/CategoryFilter.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $CustomOrderForm from "./islands/CustomOrderForm.tsx";
import * as $FilterProducts from "./islands/FilterProducts.tsx";
import * as $MapComponent from "./islands/MapComponent.tsx";
import * as $NewsletterForm from "./islands/NewsletterForm.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/contact.tsx": $contact,
    "./routes/custom.tsx": $custom,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/sustainability.tsx": $sustainability,
  },
  islands: {
    "./islands/AddToCartButton.tsx": $AddToCartButton,
    "./islands/CategoryFilter.tsx": $CategoryFilter,
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/Counter.tsx": $Counter,
    "./islands/CustomOrderForm.tsx": $CustomOrderForm,
    "./islands/FilterProducts.tsx": $FilterProducts,
    "./islands/MapComponent.tsx": $MapComponent,
    "./islands/NewsletterForm.tsx": $NewsletterForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
